### ISSUE TITLE
Django container complains "error walking file system" when venv is installed

### ISSUE THREAD

**Issue by jmoppel** [pydanny/cookiecutter-django#3083]
## What happened?
After creating a fresh project, and then docker-compose `build` and `up`, The Django Docker container infinitely complains "error walking file system".
## What should've happened instead?
The Django container should start without any errors.
## Additional details
This happens if you have a Python `venv` environment installed anywhere inside the project directory. The problem is, inside the docker container, venv symlinks to files that don't exist in the container (e.g. `/usr/bin/python3.8`).

### Steps to reproduce
Inside a new or existing cookiecutter project directory
```
docker-compose -f local.yml build
docker-compose -f local.yml up
```
Stop the containers (ctrl-c). Now, create a new python venv
```
python -m venv venv
```

Now bring up your containers and the Django Container will constantly complain "error walking file system":
```
docker-compose -f local.yml up
```
I assume this is `watchgod` complaining. Let me know if this is correct or not.

If you're open to this fix, I'll create a PR.

**Comment by luzfcb** [comment]
@jmoppel I was unable to reproduce the issue.
What operating system are you using?

If you want, could you please record the steps you made in the terminal using https://asciinema.org/ and after sending the recording link? (Be careful to avoid showing things that could compromise security, such as passwords, tokens, etc.)

Install asciinema


```bash
pip3 install asciinema
```

Create an account to able to manage your asciinema records

```bash
asciinema auth
```

Start record the steps

```bash
asciinema rec -t "cookiecutter-django issue 3083"
```

**Comment by jmoppel** [comment]
https://asciinema.org/a/L0Rzbuo6EgWi5EZpqgiOL6Vf7

One minor correction to the video. Before creating the video, I did a docker-compose build _and then_ a docker-compose up. In the video I stated it was the other way around, which is not correct.

For anyone who might find this issue in the future, the exact error message in the Docker console is:
`django          | error walking file system: FileNotFoundError [Errno 2] No such file or directory: '/app/venv/bin/python3.8'`

I have created a Docker file that corrects this problem on my machine.

**Comment by bryanus1** [comment]
I have the same error when install a venv, docker show this log: error walking file system: FileNotFoundError [Errno 2] No such file or directory: '/app/venv/bin/python'

**Comment by jmoppel** [comment]
@bryanus1 The fix I implemented to was to include the following lines in my local Django `Dockerfile` just after all the `apt-get` stuff. There's probably a cleaner way to implement than what I've done, so it doesn't break for different versions of python. However, this is what we're using at the moment.
```python
#  Prevent 'error walking file system' when Python venv exists on host
RUN ln /usr/local/bin/python3.8 /usr/bin/python
RUN ln /usr/local/bin/python3.8 /usr/bin/python3
RUN ln /usr/local/bin/python3.8 /usr/bin/python3.8
```

I'm not certain if @luzfcb would like a pull request for this, since he hasn't been able to replicate the issue.

**Comment by bryanus1** [comment]
Add lines just after `apt-get` and error persists.

![code](https://user-images.githubusercontent.com/34760958/122630244-fedd2400-d087-11eb-9560-86849b0f2180.png)
<img width="877" alt="Screen Shot 2021-06-18 at 22 53 08" src="https://user-images.githubusercontent.com/34760958/122630249-03a1d800-d088-11eb-896d-97da7bb0b586.png">

**Comment by luzfcb** [comment]
@bryanus1 try to add `venv` to the `.dockerignore` file. 
anyway, I still can't reproduce this error

**Comment by MarcelWalk** [comment]
> @bryanus1 try to add `venv` to the `.dockerignore` file.
> anyway, I still can't reproduce this error

Well I'm having the same issue.
All the previously mentioned solutions didn't worked, adding the venv to the '.dockerignore' didn't resolved it either

**Comment by bryanus1** [comment]
I realized that i can work without problem but `.dockerignore` doesn't works well

**Comment by munjata** [comment]
when removed the host virtual env (.venv) I created, its worked.

**Comment by luzfcb** [comment]
I added `venv` to the `.dockerignore` https://github.com/pydanny/cookiecutter-django/commit/18a94046b1b7b53651ce1bb23a63fd3a8e2b9b50

**Comment by jmoppel** [comment]
> Add lines just after `apt-get` and error persists.
> 
> ![code](https://user-images.githubusercontent.com/34760958/122630244-fedd2400-d087-11eb-9560-86849b0f2180.png)
> <img alt="Screen Shot 2021-06-18 at 22 53 08" width="877" src="https://user-images.githubusercontent.com/34760958/122630249-03a1d800-d088-11eb-896d-97da7bb0b586.png">

@bryanus1 Did you rebuild your containers (which is required for the symlinks to be created in your container)? Run the following before trying to bring up your containers.
``` shell
docker-compose -f local.yml build
```

**Comment by bryanus1** [comment]
> > Add lines just after `apt-get` and error persists.
> > ![code](https://user-images.githubusercontent.com/34760958/122630244-fedd2400-d087-11eb-9560-86849b0f2180.png)
> > <img alt="Screen Shot 2021-06-18 at 22 53 08" width="877" src="https://user-images.githubusercontent.com/34760958/122630249-03a1d800-d088-11eb-896d-97da7bb0b586.png">
> 
> @bryanus1 Did you rebuild your containers (which is required for the symlinks to be created in your container)? Run the following before trying to bring up your containers.
> 
> ```shell
> docker-compose -f local.yml build --no-cache
> ```

Rebuild images with this command but no works!!!

**Comment by sugud0r** [comment]
Same here. Adding `venv` to `.dockerignore` does not work... Nor rebuilding without cache. Also, renaming the folder to whatever else reproduce the same error.

**Comment by jmoppel** [comment]
@bryanus1 Make a note of where the symlink `venv/bin/python' points to. Shell into your container and see if that path exists in your container. If it doesn't, that's your problem. As I described in my initial post, the crux of the issue I had is that the symlink to the python executable in `venv/bin/`is broken because the path it's pointing to exists on your host machine, but not in the container.

**Comment by bryanus1** [comment]
@jmoppel `venv/bin/python` has symlink to python in my local machine and not into container, that's is problem. How I resolve it?

**Comment by ruslaniv** [comment]
I had the same problem, here is how I solved it.

In a docker container there is no need to create a virtual environment, since docker *is* akin to a virtual environment, so in a container we can ```pip install``` all packages globally.
So when we spin up a container with a ```docker compose up```, mapping an app folder from the host to a folder in a container, it is important to omit mapping the venv folder from the host, otherwise python gets confused, since now there is a symlink for ```app/venv/bin/python``` inside a container pointing to a python interpreter location from the host operating system.
So a way to omit mapping venv from the host to a container is add this into docker-compose:

```
 volumes:
      - .:/app
      - app/venv/ # This line hides mapping of venv folder in the container
 ```

**Comment by bryanus1** [comment]
> I had the same problem, here is how I solved it.
> 
> In a docker container there is no need to create a virtual environment, since docker _is_ akin to a virtual environment, so in a container we can `pip install` all packages globally.
> So when we spin up a container with a `docker compose up`, mapping an app folder from the host to a folder in a container, it is important to omit mapping the venv folder from the host, otherwise python gets confused, since now there is a symlink for `app/venv/bin/python` inside a container pointing to a python interpreter location from the host operating system.
> So a way to omit mapping venv from the host to a container is add this into docker-compose:
> 
> ```
>  volumes:
>       - .:/app
>       - app/venv/ # This line hides mapping of venv folder in the container
> ```

I test your solution and works without problems, only make a change that volume must be a absolutly path, change 
`volumes:
      - .:/app
      - /app/venv/` add un ´/´ before ´app´

**Comment by jmoppel** [comment]
It looks like this is a known issue with Watchgod that has an open pull request to fix the issue.

https://github.com/samuelcolvin/watchgod/issues/80

**Comment by oesah** [comment]
In my case, @bryanus1 's solution worked:

```
    ...
    volumes:
      - .:/app:z
      - /app/.venv
```
