### ISSUE TITLE
Debugging on Heroku with Stock Settings

### ISSUE THREAD

**Issue by dogukantufekci** [pydanny/cookiecutter-django#387]
I've never used mailgun and redis before, and I'm having issues with my default settings.

I committed my repo to Heroku with stock settings, and the website loads fine. However, when I try to signup, I get 500 Error. However, I see what user account is already created.

I don't get any admin emails for errors.

I try to see logs using 'heroku logs' however no error logs.

PLEASE TELL ME WHATS WRONG

**Comment by jayfk** [comment]
Try to send a mail in a try/except block from a view with fail_silently=False and print the traceback so that the error appears in your logs. As a last resort you can always fall back to set DEBUG=True, but make sure to change all your secret keys and credentials afterwards.

**Comment by pydanny** [comment]
@dogukantufekci Did you resolve this? If you have, let me know so we can close it

**Comment by dogukantufekci** [comment]
@pydanny I haven't tried it. However, I will let you know as soon as possible.

**Comment by stepmr** [comment]
@pydanny @dogukantufekci I just deployed to heroku using the docs.. I'm not encountering any issues...

**Comment by EricZaporzan** [comment]
For anyone still experiencing this problem: make sure you're using the correct MailGun API key for the Heroku setup. There are public and private API keys found on the main page of the [dashboard](https://mailgun.com/app/dashboard) but the key one should be using is on the relevant Domain Information page. 

Silly, I know, but I spent half an hour trying to figure out where I was messing up.

**Comment by pydanny** [comment]
Closing this as it has not had traffic for some time.
